# Generated by Django 5.2.8 on 2026-05-10 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, default='TEMP_TXN_ID', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='api_reserva_status_b87e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time'], name='api_reserva_start_t_c4841f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_time'], name='api_reserva_end_tim_8fdc92_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['active'], name='api_session_active_fdc8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['entry_time'], name='api_session_entry_t_88a450_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['updated_at'], name='api_vehicle_updated_219de7_idx'),
        ),
    ]
